cwist: src/sys/session/session_manager.c File Reference
session_manager.c File Reference
Session allocation helpers built from a resettable arena and RC payloads.
#include <cwist/sys/session/session_manager.h>
#include <cwist/core/mem/alloc.h>
#include <stdlib.h>
#include <string.h>
Functions
void session_arena_init (struct session_arena *arena, uint8_t *buffer, size_t capacity)
Initialize a linear arena over caller-provided storage.
void * session_arena_alloc (struct session_arena *arena, size_t size)
Allocate aligned bytes from the request arena.
void session_arena_reset (struct session_arena *arena)
Rewind the arena so subsequent allocations reuse the full buffer.
void session_rc_init (struct session_rc_header *header, void(*destructor)(void *))
Initialize the reference-count metadata for a shared payload.
void * session_shared_alloc (size_t payload_size, void(*destructor)(void *))
Allocate a shared payload with an in-band reference-count header.
void session_shared_inc (void *payload)
Increment the reference count for a shared payload.
void session_shared_dec (void *payload)
Drop a reference and destroy the payload when the count reaches zero.
void session_manager_init (struct session_manager *manager, uint8_t *buffer, size_t capacity)
Initialize the request-scoped allocator state for a session manager.
void session_manager_reset (struct session_manager *manager)
Reset all request-scoped allocations owned by the manager.
Detailed Description
Session allocation helpers built from a resettable arena and RC payloads.
Definition in file session_manager.c.
Function Documentation
session_arena_alloc()
void * session_arena_alloc (struct session_arena * arena, size_t size)
Allocate aligned bytes from the request arena.
Allocate aligned storage from the request arena.
Parameters
arena Arena that owns the backing storage.
size Number of bytes requested before alignment.
Returns
Pointer to a contiguous region, or NULL when the arena is exhausted.
Definition at line 30 of file session_manager.c.
session_arena_init()
void session_arena_init (struct session_arena * arena, uint8_t * buffer, size_t capacity)
Initialize a linear arena over caller-provided storage.
Bind a caller-owned buffer to a session arena and reset its cursor.
Parameters
arena Arena to initialize.
buffer Backing storage to consume sequentially.
capacity Total number of bytes available in buffer.
Definition at line 17 of file session_manager.c.
Referenced by session_manager_init().
session_arena_reset()
void session_arena_reset (struct session_arena * arena)
Rewind the arena so subsequent allocations reuse the full buffer.
Reset the request arena so future allocations reuse the full buffer.
Parameters
arena Arena to reset.
Definition at line 45 of file session_manager.c.
Referenced by session_manager_reset().
session_manager_init()
void session_manager_init (struct session_manager * manager, uint8_t * buffer, size_t capacity)
Initialize the request-scoped allocator state for a session manager.
Initialize a session manager around a caller-supplied arena buffer.
Parameters
manager Manager to initialize.
buffer Backing arena storage.
capacity Size of buffer in bytes.
Definition at line 111 of file session_manager.c.
References session_arena_init().
session_manager_reset()
void session_manager_reset (struct session_manager * manager)
Reset all request-scoped allocations owned by the manager.
Parameters
manager Manager whose arena should be rewound.
Definition at line 120 of file session_manager.c.
References session_arena_reset().
session_rc_init()
void session_rc_init (struct session_rc_header * header, void(* destructor)(void *))
Initialize the reference-count metadata for a shared payload.
Initialize the metadata that tracks a shared session allocation.
Parameters
header Header that precedes the payload.
destructor Optional callback run just before the payload is freed.
Definition at line 55 of file session_manager.c.
Referenced by session_shared_alloc().
session_shared_alloc()
void * session_shared_alloc (size_t payload_size, void(* destructor)(void *))
Allocate a shared payload with an in-band reference-count header.
Allocate a zeroed payload preceded by a reference-count header.
Parameters
payload_size Number of bytes visible to callers.
destructor Optional callback invoked before memory is released.
Returns
Zeroed payload pointer, or NULL when allocation fails.
Definition at line 67 of file session_manager.c.
References session_rc_init().
session_shared_dec()
void session_shared_dec (void * payload)
Drop a reference and destroy the payload when the count reaches zero.
Decrement the reference count and free the payload when it reaches zero.
Parameters
payload Payload returned by session_shared_alloc().
Definition at line 92 of file session_manager.c.
session_shared_inc()
void session_shared_inc (void * payload)
Increment the reference count for a shared payload.
Parameters
payload Payload returned by session_shared_alloc().
Definition at line 82 of file session_manager.c.