cwist: src/core/mem/alloc.c File Reference
alloc.c File Reference
Memory allocation bridge that can route CWIST allocations through libttak owner guards.
#include <cwist/core/mem/alloc.h>
#include <ttak/mem/mem.h>
#include <ttak/timing/timing.h>
#include <ttak/sync/sync.h>
#include <cjson/cJSON.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <stdlib.h>
#include <stdatomic.h>
Functions
ttak_owner_t * cwist_create_owner (void)
Create or return the shared owner context used for guarded memory operations.
void * cwist_malloc (size_t size)
Allocate zeroed memory either via calloc or the libttak owner context.
void * cwist_alloc (size_t size)
Alias of cwist_malloc for CWIST's preferred naming.
void * cwist_alloc_array (size_t count, size_t elem_size)
Allocate zeroed storage for a fixed number of elements.
void * cwist_realloc (void *ptr, size_t new_size)
Resize an existing allocation while preserving its previous contents.
char * cwist_strdup (const char *src)
Duplicate a NUL-terminated string into CWIST-managed storage.
char * cwist_strndup (const char *src, size_t n)
Duplicate at most n bytes of a string into CWIST-managed storage.
void cwist_free (void *ptr)
Free a CWIST-managed allocation, honoring guarded-owner mode when enabled.
__attribute__ ((constructor))
Install cJSON hooks so JSON allocations share CWIST's memory strategy.
__attribute__ ((destructor))
Destructor hook that releases the shared owner context on process exit.
Detailed Description
Memory allocation bridge that can route CWIST allocations through libttak owner guards.
Definition in file alloc.c.
Function Documentation
cwist_alloc()
void * cwist_alloc (size_t size)
Alias of cwist_malloc for CWIST's preferred naming.
Allocate zeroed memory tracked by libttak.
Parameters
size Requested allocation size in bytes.
Returns
Zeroed memory block, or NULL when allocation fails.
Definition at line 221 of file alloc.c.
References cwist_malloc().
cwist_alloc_array()
void * cwist_alloc_array (size_t count, size_t elem_size)
Allocate zeroed storage for a fixed number of elements.
Allocate zeroed memory for count elements.
Parameters
count Number of elements requested.
elem_size Size of each element in bytes.
Returns
Zeroed array allocation, or NULL when overflow or allocation fails.
Definition at line 231 of file alloc.c.
References cwist_malloc().
cwist_create_owner()
ttak_owner_t * cwist_create_owner (void)
Create or return the shared owner context used for guarded memory operations.
Lazily create (or return) the shared CWIST owner context.
Returns
Shared libttak owner context, or NULL when initialization fails.
Definition at line 141 of file alloc.c.
cwist_free()
void cwist_free (void * ptr)
Free a CWIST-managed allocation, honoring guarded-owner mode when enabled.
Free memory obtained via cwist_alloc/cwist_strdup/etc.
Parameters
ptr Allocation previously returned by CWIST memory helpers.
Definition at line 315 of file alloc.c.
cwist_malloc()
void * cwist_malloc (size_t size)
Allocate zeroed memory either via calloc or the libttak owner context.
Allocate zeroed memory via the CWIST owner context.
Parameters
size Requested allocation size in bytes.
Returns
Zeroed memory block, or NULL when allocation fails.
Definition at line 200 of file alloc.c.
Referenced by cwist_alloc(), cwist_alloc_array(), cwist_realloc(), cwist_strdup(), and cwist_strndup().
cwist_realloc()
void * cwist_realloc (void * ptr, size_t new_size)
Resize an existing allocation while preserving its previous contents.
Resize an existing allocation (libttak tracked).
Parameters
ptr Existing allocation, or NULL to behave like malloc.
new_size Requested new size in bytes.
Returns
Resized allocation, or NULL when reallocation fails.
Definition at line 247 of file alloc.c.
References cwist_malloc().
cwist_strdup()
char * cwist_strdup (const char * src)
Duplicate a NUL-terminated string into CWIST-managed storage.
Duplicate a string using libttak-backed storage.
Parameters
src Source string to duplicate.
Returns
Duplicated string, or NULL when the source is NULL or allocation fails.
Definition at line 272 of file alloc.c.
References cwist_malloc().
cwist_strndup()
char * cwist_strndup (const char * src, size_t n)
Duplicate at most n bytes of a string into CWIST-managed storage.
Duplicate up to n bytes of a string (libttak-backed).
Parameters
src Source string to duplicate.
n Maximum number of source bytes to copy.
Returns
Duplicated string, or NULL when the source is NULL or allocation fails.
Definition at line 301 of file alloc.c.
References cwist_malloc().