cwist: src/core/db/db.c File Reference
db.c File Reference
SQLite convenience wrappers plus lightweight heuristics for query execution and JSON healing.
#include <cwist/core/db/sql.h>
#include <cwist/core/utils/json_heal.h>
#include <cwist/core/utils/zod.h>
#include <cwist/sys/err/cwist_err.h>
#include <cwist/core/mem/alloc.h>
#include <sqlite3.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
Functions
cwist_error_t cwist_db_open (cwist_db **db, const char *path)
Open a SQLite database and wrap the resulting connection in a CWIST handle.
void cwist_db_close (cwist_db *db)
Close a CWIST database wrapper and its underlying SQLite connection.
cwist_error_t cwist_db_exec (cwist_db *db, const char *sql)
Execute an arbitrary SQL statement string without returning rows.
cwist_error_t cwist_db_query (cwist_db *db, const char *sql, cJSON **result)
Execute a SQL query and collect every row into a cJSON array.
cwist_error_t cwist_db_insert_healed (cwist_db *db, const char *table, const char *json_str, const cwist_schema_t *schema, const cwist_heal_config_t *heal_cfg)
Heal, validate, and insert a JSON object into a table.
cwist_error_t cwist_db_query_strict (cwist_db *db, const char *sql, cJSON **result, const cwist_schema_t *schema)
Execute a query and require the result rows to satisfy a CWIST schema.
Detailed Description
SQLite convenience wrappers plus lightweight heuristics for query execution and JSON healing.
Definition in file db.c.
Function Documentation
cwist_db_close()
void cwist_db_close (cwist_db * db)
Close a CWIST database wrapper and its underlying SQLite connection.
Parameters
db Database wrapper to close.
Definition at line 185 of file db.c.
cwist_db_exec()
cwist_error_t cwist_db_exec (cwist_db * db, const char * sql)
Execute an arbitrary SQL statement string without returning rows.
Parameters
db Open database wrapper.
sql SQL text to execute.
Returns
Tagged CWIST error describing success or failure.
Definition at line 202 of file db.c.
Referenced by cwist_db_insert_healed().
cwist_db_insert_healed()
cwist_error_t cwist_db_insert_healed (cwist_db * db, const char * table, const char * json_str, const cwist_schema_t * schema, const cwist_heal_config_t * heal_cfg)
Heal, validate, and insert a JSON object into a table.
Insert a (possibly broken) JSON object into a table with self-healing.
Parameters
db Open database wrapper.
table Destination table name.
json_str Raw JSON input to heal and insert.
schema Optional schema used for alignment and validation.
heal_cfg Optional healing configuration overrides.
Returns
Tagged CWIST error describing success or failure.
Definition at line 400 of file db.c.
References cwist_db_exec(), cwist_heal_result_free(), cwist_json_heal(), cwist_zod_parse(), cwist_zod_print_errors(), cwist_heal_result::json, cwist_heal_config::schema, and cwist_heal_config::threshold.
cwist_db_open()
cwist_error_t cwist_db_open (cwist_db ** db, const char * path)
Open a SQLite database and wrap the resulting connection in a CWIST handle.
Parameters
db Output pointer receiving the allocated database wrapper.
path Filesystem path or SQLite URI to open.
Returns
Tagged CWIST error describing success or failure.
Definition at line 152 of file db.c.
cwist_db_query()
cwist_error_t cwist_db_query (cwist_db * db, const char * sql, cJSON ** result)
Execute a SQL query and collect every row into a cJSON array.
Parameters
db Open database wrapper.
sql SQL text to execute.
result Output pointer receiving the cJSON row array.
Returns
Tagged CWIST error describing success or failure.
Definition at line 264 of file db.c.
Referenced by cwist_db_query_strict().
cwist_db_query_strict()
cwist_error_t cwist_db_query_strict (cwist_db * db, const char * sql, cJSON ** result, const cwist_schema_t * schema)
Execute a query and require the result rows to satisfy a CWIST schema.
Execute a SELECT query and strictly validate each result row.
Parameters
db Open database wrapper.
sql SQL text to execute.
result Output pointer receiving the cJSON row array on success.
schema Schema applied to every returned row.
Returns
Tagged CWIST error describing success or validation failure.
Definition at line 473 of file db.c.
References cwist_db_query(), and cwist_zod_validate().