cwist: src/core/utils/zod.c File Reference
zod.c File Reference
Lightweight schema validation helpers for cJSON payloads.
#include <cwist/core/utils/zod.h>
#include <stdio.h>
#include <string.h>
Functions
cwist_zod_result_t cwist_zod_validate (const cJSON *json, const cwist_schema_t *schema)
Validate a parsed JSON object against a flat CWIST schema.
cwist_zod_result_t cwist_zod_parse (const char *raw, const cwist_schema_t *schema, cJSON **out)
Parse raw JSON text and validate it against a CWIST schema.
void cwist_zod_print_errors (const cwist_zod_result_t *r)
Print validation errors to stderr using the built-in ZOD-like format.
Detailed Description
Lightweight schema validation helpers for cJSON payloads.
Definition in file zod.c.
Function Documentation
cwist_zod_parse()
cwist_zod_result_t cwist_zod_parse (const char * raw, const cwist_schema_t * schema, cJSON ** out)
Parse raw JSON text and validate it against a CWIST schema.
Parse a raw JSON string and validate it in one step.
Parameters
raw Raw JSON text to parse.
schema Expected field list and type requirements.
out Optional output pointer that receives the parsed cJSON object on success.
Returns
Validation result containing success flag and collected errors.
Definition at line 114 of file zod.c.
References cwist_zod_validate().
Referenced by cwist_db_insert_healed().
cwist_zod_print_errors()
void cwist_zod_print_errors (const cwist_zod_result_t * r)
Print validation errors to stderr using the built-in ZOD-like format.
Print all validation errors to stderr.
Parameters
r Validation result to print.
Definition at line 147 of file zod.c.
Referenced by cwist_db_insert_healed().
cwist_zod_validate()
cwist_zod_result_t cwist_zod_validate (const cJSON * json, const cwist_schema_t * schema)
Validate a parsed JSON object against a flat CWIST schema.
Strictly validate an already-parsed cJSON object against a schema.
Parameters
json Parsed JSON object to inspect.
schema Expected field list and type requirements.
Returns
Validation result containing success flag and collected errors.
Definition at line 65 of file zod.c.
References cwist_schema_field::name, cwist_schema_field::required, and cwist_schema_field::type.
Referenced by cwist_db_query_strict(), and cwist_zod_parse().