cwist: src/net/websocket/websocket.c File Reference
websocket.c File Reference
WebSocket handshake and frame transport helpers for CWIST handlers.
#include <cwist/net/websocket/websocket.h>
#include <cwist/net/http/http.h>
#include <cwist/core/mem/alloc.h>
#include "ws_utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <errno.h>
Functions
cwist_websocket * cwist_websocket_upgrade (cwist_http_request *req, int client_fd)
Upgrade an HTTP request to a WebSocket connection.
cwist_ws_frame * cwist_websocket_receive (cwist_websocket *ws)
Receive the next WebSocket frame from a connected client.
int cwist_websocket_send (cwist_websocket *ws, cwist_ws_opcode_t opcode, const uint8_t *data, size_t len)
Send a single FIN-terminated WebSocket frame to the peer.
void cwist_websocket_frame_destroy (cwist_ws_frame *frame)
Release a frame and its owned payload buffer.
void cwist_websocket_close (cwist_websocket *ws)
Initiate a close handshake for the WebSocket wrapper.
void cwist_websocket_destroy (cwist_websocket *ws)
Destroy the WebSocket wrapper without closing the underlying socket.
Detailed Description
WebSocket handshake and frame transport helpers for CWIST handlers.
Definition in file websocket.c.
Function Documentation
cwist_websocket_close()
void cwist_websocket_close (cwist_websocket * ws)
Initiate a close handshake for the WebSocket wrapper.
Parameters
ws Connection to close. NULL is ignored.
Definition at line 229 of file websocket.c.
References cwist_websocket_send().
cwist_websocket_destroy()
void cwist_websocket_destroy (cwist_websocket * ws)
Destroy the WebSocket wrapper without closing the underlying socket.
Parameters
ws Wrapper to release. NULL is ignored.
Definition at line 240 of file websocket.c.
cwist_websocket_frame_destroy()
void cwist_websocket_frame_destroy (cwist_ws_frame * frame)
Release a frame and its owned payload buffer.
Parameters
frame Frame object to destroy. NULL is ignored.
Definition at line 218 of file websocket.c.
cwist_websocket_receive()
cwist_ws_frame * cwist_websocket_receive (cwist_websocket * ws)
Receive the next WebSocket frame from a connected client.
Receive a frame, blocking until data arrives or the socket closes.
Client frames are required to be masked by RFC 6455, so unmasked payloads are rejected. Payload data is copied into a heap buffer and null-terminated for convenience when the caller interprets a text frame as a C string.
Parameters
ws WebSocket connection wrapper returned by cwist_websocket_upgrade().
Returns
Newly allocated frame, or NULL when the connection is closed or invalid.
Definition at line 105 of file websocket.c.
cwist_websocket_send()
int cwist_websocket_send (cwist_websocket * ws, cwist_ws_opcode_t opcode, const uint8_t * data, size_t len)
Send a single FIN-terminated WebSocket frame to the peer.
Send a frame with the specified opcode and payload.
Parameters
ws Active WebSocket connection wrapper.
opcode WebSocket opcode describing the payload semantics.
data Optional payload buffer. May be NULL when len is zero.
len Number of payload bytes to transmit.
Returns
0 on success, or -1 when the socket write fails.
Definition at line 181 of file websocket.c.
Referenced by cwist_websocket_close().
cwist_websocket_upgrade()
cwist_websocket * cwist_websocket_upgrade (cwist_http_request * req, int client_fd)
Upgrade an HTTP request to a WebSocket connection.
Upgrade a standard HTTP request to a WebSocket connection.
The function validates the required upgrade headers, computes the Sec-WebSocket-Accept response, emits the 101 Switching Protocols reply, and returns a lightweight wrapper around the already-open client socket.
Parameters
req Parsed HTTP request that requested the upgrade.
client_fd Accepted client socket descriptor.
Returns
WebSocket wrapper on success, or NULL when the handshake fails.
Definition at line 32 of file websocket.c.
References base64_encode(), cwist_http_header_add(), cwist_http_header_get(), cwist_http_response_create(), cwist_http_response_destroy(), cwist_http_send_response(), sha1(), and cwist_http_response::status_text.