cwist: include/cwist/core/utils/zod.h File Reference
zod.h File Reference
Strict JSON schema validation (Zod-style) for CWIST.
#include <cwist/core/utils/json_heal.h>
#include <cjson/cJSON.h>
#include <stdbool.h>
Classes
struct cwist_zod_error
A single validation failure.
struct cwist_zod_result
Result returned by cwist_zod_validate() / cwist_zod_parse().
Typedefs
typedef struct cwist_zod_error cwist_zod_error_t
A single validation failure.
typedef struct cwist_zod_result cwist_zod_result_t
Result returned by cwist_zod_validate() / cwist_zod_parse().
Functions
cwist_zod_result_t cwist_zod_validate (const cJSON *json, const cwist_schema_t *schema)
Strictly validate an already-parsed cJSON object against a schema.
cwist_zod_result_t cwist_zod_parse (const char *raw, const cwist_schema_t *schema, cJSON **out)
Parse a raw JSON string and validate it in one step.
void cwist_zod_print_errors (const cwist_zod_result_t *r)
Print all validation errors to stderr.
Detailed Description
Strict JSON schema validation (Zod-style) for CWIST.
Unlike the self-healing layer, this module rejects data that does not conform to the schema. Use it at trust boundaries (HTTP API inputs, DB writes) where silent coercion is undesirable.
It shares the cwist_schema_t / cwist_schema_field_t types defined in json_heal.h so the same schema descriptor can drive both healing and strict validation.
Usage:
cwist_zod_result_t r = cwist_zod_parse(raw_body, &my_schema, &parsed);
if (!r.valid) {
    cwist_zod_print_errors(&r);
    // respond 400
}
// use parsed …
cJSON_Delete(parsed);
Definition in file zod.h.
Function Documentation
cwist_zod_parse()
cwist_zod_result_t cwist_zod_parse (const char * raw, const cwist_schema_t * schema, cJSON ** out)
Parse a raw JSON string and validate it in one step.
On success *out is set to the parsed cJSON tree; the caller must call cJSON_Delete(*out) when done. On failure *out is set to NULL.
Parameters
raw Null-terminated JSON string.
schema Schema descriptor.
out [out] Parsed cJSON tree on success, NULL otherwise.
Returns
Validation result. Check result.valid AND *out != NULL.
Parse a raw JSON string and validate it in one step.
Parameters
raw Raw JSON text to parse.
schema Expected field list and type requirements.
out Optional output pointer that receives the parsed cJSON object on success.
Returns
Validation result containing success flag and collected errors.
Definition at line 114 of file zod.c.
References cwist_zod_validate().
Referenced by cwist_db_insert_healed().
cwist_zod_print_errors()
void cwist_zod_print_errors (const cwist_zod_result_t * r)
Print all validation errors to stderr.
Print all validation errors to stderr.
Parameters
r Validation result to print.
Definition at line 147 of file zod.c.
Referenced by cwist_db_insert_healed().
cwist_zod_validate()
cwist_zod_result_t cwist_zod_validate (const cJSON * json, const cwist_schema_t * schema)
Strictly validate an already-parsed cJSON object against a schema.
Checks:
All required fields are present.
All fields that appear in the schema have the declared type.
No type coercion is performed; use cwist_json_heal() first if coercion is acceptable.
Parameters
json cJSON object (not array / primitive).
schema Schema descriptor.
Returns
Validation result. result.valid == true iff all checks pass.
Strictly validate an already-parsed cJSON object against a schema.
Parameters
json Parsed JSON object to inspect.
schema Expected field list and type requirements.
Returns
Validation result containing success flag and collected errors.
Definition at line 65 of file zod.c.
References cwist_schema_field::name, cwist_schema_field::required, and cwist_schema_field::type.
Referenced by cwist_db_query_strict(), and cwist_zod_parse().