cwist: src/net/http/query.c File Reference
query.c File Reference
Hash-map based storage and parsing helpers for URL query parameters.
#include <cwist/net/http/query.h>
#include <cwist/core/siphash/siphash.h>
#include <cwist/core/mem/alloc.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <uriparser/Uri.h>
Functions
cwist_query_map * cwist_query_map_create (void)
Allocate a query map and seed its SipHash key material.
void cwist_query_map_destroy (cwist_query_map *map)
Release every bucket node and the map container itself.
void cwist_query_map_clear (cwist_query_map *map)
Remove every key/value pair while keeping the bucket array allocated.
void cwist_query_map_set (cwist_query_map *map, const char *key, const char *value)
Insert or replace a decoded query parameter in the map.
const char * cwist_query_map_get (cwist_query_map *map, const char *key)
Look up a decoded query parameter by key.
void cwist_query_map_parse (cwist_query_map *map, const char *raw_query)
Parse a raw a=1&b=2 query string into the existing map.
Detailed Description
Hash-map based storage and parsing helpers for URL query parameters.
Definition in file query.c.
Function Documentation
cwist_query_map_clear()
void cwist_query_map_clear (cwist_query_map * map)
Remove every key/value pair while keeping the bucket array allocated.
Parameters
map Query map to clear in-place.
Definition at line 51 of file query.c.
Referenced by cwist_query_map_destroy().
cwist_query_map_create()
cwist_query_map * cwist_query_map_create (void)
Allocate a query map and seed its SipHash key material.
Returns
Newly allocated map, or NULL when memory allocation fails.
Definition at line 21 of file query.c.
Referenced by cwist_http_request_create().
cwist_query_map_destroy()
void cwist_query_map_destroy (cwist_query_map * map)
Release every bucket node and the map container itself.
Parameters
map Query map to destroy.
Definition at line 40 of file query.c.
References cwist_query_map_clear().
cwist_query_map_get()
const char * cwist_query_map_get (cwist_query_map * map, const char * key)
Look up a decoded query parameter by key.
Parameters
map Query map to search.
key Decoded key to retrieve.
Returns
Stored value, or NULL when the key is absent.
Definition at line 104 of file query.c.
cwist_query_map_parse()
void cwist_query_map_parse (cwist_query_map * map, const char * raw_query)
Parse a raw a=1&b=2 query string into the existing map.
Parse raw query strings (e.g., "a=1&b=2") into the map.
Parameters
map Destination map that receives decoded keys and values.
raw_query Raw query substring without the leading question mark.
Definition at line 125 of file query.c.
References cwist_query_map_set().
cwist_query_map_set()
void cwist_query_map_set (cwist_query_map * map, const char * key, const char * value)
Insert or replace a decoded query parameter in the map.
Parameters
map Query map that owns the entry storage.
key Decoded query-string key.
value Decoded query-string value.
Definition at line 72 of file query.c.
Referenced by cwist_query_map_parse().