cwist: src/sys/app/big_dumb_reply.c File Reference
big_dumb_reply.c File Reference
Opportunistic response cache that stores stable GET replies in memory or on disk.
#include <cwist/sys/app/big_dumb_reply.h>
#include <cwist/core/mem/alloc.h>
#include <cwist/core/siphash/siphash.h>
#include <cwist/sys/sys_info.h>
#include <cwist/core/macros.h>
#include <sqlite3.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <limits.h>
Functions
cwist_bdr_t * cwist_bdr_create (void)
Allocate and initialize the Big Dumb Reply cache.
void cwist_bdr_destroy (cwist_bdr_t *bdr)
Destroy the cache and every response blob it currently owns.
const void * cwist_bdr_get (cwist_bdr_t *bdr, const char *method, const char *path, size_t *out_len)
Look up a previously stabilized GET response in the cache.
void cwist_bdr_put (cwist_bdr_t *bdr, const char *method, const char *path, const void *data, size_t len)
Feed a candidate GET response into the cache and promote stable blobs.
void cwist_bdr_set_limits (cwist_bdr_t *bdr, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Adjusts guard-rail policies for the in-memory cache.
Detailed Description
Opportunistic response cache that stores stable GET replies in memory or on disk.
Definition in file big_dumb_reply.c.
Function Documentation
cwist_bdr_create()
cwist_bdr_t * cwist_bdr_create (void)
Allocate and initialize the Big Dumb Reply cache.
Creates a BDR context.
Returns
Newly allocated cache object, or NULL on allocation failure.
Definition at line 165 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, cwist_bdr_t::current_bytes, cwist_bdr_t::disk_db, cwist_bdr_t::gc_cursor, cwist_bdr_t::is_disk_mode, cwist_bdr_t::latency_threshold_ms, cwist_bdr_t::max_bytes, cwist_bdr_t::max_entry_age_sec, and cwist_bdr_t::revalidate_hits.
Referenced by cwist_app_create().
cwist_bdr_destroy()
void cwist_bdr_destroy (cwist_bdr_t * bdr)
Destroy the cache and every response blob it currently owns.
Destroys a BDR context and frees all cached blobs.
Parameters
bdr Cache instance to destroy.
Definition at line 185 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, and cwist_bdr_t::disk_db.
Referenced by cwist_app_destroy().
cwist_bdr_get()
const void * cwist_bdr_get (cwist_bdr_t * bdr, const char * method, const char * path, size_t * out_len)
Look up a previously stabilized GET response in the cache.
Try to find a cached response.
Parameters
bdr Cache instance to query.
method HTTP method string.
path Canonical request path.
out_len Optional output pointer that receives the blob length.
Returns
Cached response blob, or NULL when absent/unstable/invalidated.
Definition at line 282 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, bdr_entry_t::hits, cwist_bdr_t::is_disk_mode, bdr_entry_t::is_stable, bdr_entry_t::len, bdr_entry_t::request_hash, and bdr_entry_t::response_blob.
cwist_bdr_put()
void cwist_bdr_put (cwist_bdr_t * bdr, const char * method, const char * path, const void * data, size_t len)
Feed a candidate GET response into the cache and promote stable blobs.
Store a response in the cache.
Parameters
bdr Cache instance to update.
method HTTP method string.
path Canonical request path.
data Serialized response bytes.
len Number of bytes in data.
Definition at line 357 of file big_dumb_reply.c.
References cwist_bdr_t::bucket_count, cwist_bdr_t::buckets, bdr_entry_t::created_at, cwist_bdr_t::current_bytes, cwist_bdr_t::disk_db, bdr_entry_t::hits, cwist_bdr_t::is_disk_mode, bdr_entry_t::is_stable, bdr_entry_t::len, bdr_entry_t::request_hash, bdr_entry_t::response_blob, and bdr_entry_t::response_hash.
cwist_bdr_set_limits()
void cwist_bdr_set_limits (cwist_bdr_t * bdr, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Adjusts guard-rail policies for the in-memory cache.
Parameters
bdr Context.
max_bytes Maximum bytes to keep in RAM (0 keeps default).
max_entry_age_sec Time-to-live for cached entries (<=0 keeps default).
revalidate_hits Force relearning after this many hits (0 keeps default).
Definition at line 539 of file big_dumb_reply.c.
References cwist_bdr_t::max_bytes, cwist_bdr_t::max_entry_age_sec, and cwist_bdr_t::revalidate_hits.
Referenced by cwist_app_configure_bdr().