cwist: src/core/utils/json_heal.c File Reference
json_heal.c File Reference
Multi-stage JSON recovery pipeline with optional schema alignment.
#include <cwist/core/utils/json_heal.h>
#include <cwist/core/mem/alloc.h>
#include <cjson/cJSON.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Functions
int cwist_json_schema_align (cJSON *obj, const cwist_schema_t *schema, char *log, size_t log_sz)
Apply L2 schema alignment to an already-parsed cJSON object in place.
cwist_heal_result_t cwist_json_heal (const char *input, const cwist_heal_config_t *cfg)
Recover malformed JSON using syntax repair, schema alignment, and an optional callback.
void cwist_heal_result_free (cwist_heal_result_t *r)
Free heap storage owned by a healing result.
Detailed Description
Multi-stage JSON recovery pipeline with optional schema alignment.
Definition in file json_heal.c.
Function Documentation
cwist_heal_result_free()
void cwist_heal_result_free (cwist_heal_result_t * r)
Free heap storage owned by a healing result.
Free resources owned by a cwist_heal_result_t.
Parameters
r Result object previously populated by cwist_json_heal().
Definition at line 452 of file json_heal.c.
References cwist_heal_result::json.
Referenced by cwist_db_insert_healed().
cwist_json_heal()
cwist_heal_result_t cwist_json_heal (const char * input, const cwist_heal_config_t * cfg)
Recover malformed JSON using syntax repair, schema alignment, and an optional callback.
Attempt to heal a potentially broken JSON string.
The function first attempts a direct parse, then falls back to the internal L1 syntax healer, and finally consults the user-provided SLLM callback when configured. Each successful step records the recovery level, confidence, and a short operator-facing log of the transformations that were applied.
Parameters
input Raw JSON text that may contain structural defects.
cfg Optional recovery configuration. NULL applies the built-in defaults.
Returns
Result structure describing the best recovery path that succeeded.
Definition at line 375 of file json_heal.c.
References cwist_heal_result::confidence, cwist_json_schema_align(), cwist_heal_result::healed, cwist_heal_result::json, cwist_heal_result::level, cwist_heal_result::log, cwist_heal_config::schema, cwist_heal_config::sllm_fn, cwist_heal_config::sllm_userdata, and cwist_heal_config::threshold.
Referenced by cwist_db_insert_healed().
cwist_json_schema_align()
int cwist_json_schema_align (cJSON * obj, const cwist_schema_t * schema, char * log, size_t log_sz)
Apply L2 schema alignment to an already-parsed cJSON object in place.
Renames aliased / fuzzy-matched field names to their canonical forms and coerces mismatched types (e.g. "123" → 123 for an INT field).
Parameters
obj cJSON object to modify in place.
schema Schema descriptor.
log Optional output buffer for change description.
log_sz Size of log buffer.
Returns
Number of fields modified, or -1 on error.
Definition at line 230 of file json_heal.c.
References cwist_schema_field::aliases, cwist_schema_field::name, and cwist_schema_field::type.
Referenced by cwist_json_heal().