cwist: src/net/http/https.c File Reference
https.c File Reference
OpenSSL-backed HTTPS accept, receive, send, and server-loop helpers.
#include <cwist/net/http/https.h>
#include <cwist/core/sstring/sstring.h>
#include <cwist/sys/err/cwist_err.h>
#include <cwist/core/mem/alloc.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <poll.h>
#include <sys/socket.h>
#include <arpa/inet.h>
Functions
cwist_error_t cwist_https_init_context (cwist_https_context **ctx, const char *cert_path, const char *key_path)
Initialize OpenSSL and create a server TLS context from PEM files.
void cwist_https_destroy_context (cwist_https_context *ctx)
Free an HTTPS context and release its OpenSSL resources.
cwist_error_t cwist_https_accept (cwist_https_context *ctx, int client_fd, cwist_https_connection **conn)
Wrap an accepted TCP client socket in an OpenSSL connection object.
void cwist_https_close_connection (cwist_https_connection *conn)
Gracefully close an HTTPS connection and free its buffers.
cwist_http_request * cwist_https_receive_request (cwist_https_connection *conn)
Read from the TLS stream until a full HTTP request has been assembled.
cwist_error_t cwist_https_send_response (cwist_https_connection *conn, cwist_http_response *res)
Serialize an HTTP response and send it over an active TLS connection.
cwist_error_t cwist_https_server_loop (int server_fd, cwist_https_context *ctx, void(*handler)(cwist_https_connection *, void *), void *user_ctx)
Accept HTTPS clients in a loop and dispatch each one to the supplied handler.
Detailed Description
OpenSSL-backed HTTPS accept, receive, send, and server-loop helpers.
Definition in file https.c.
Function Documentation
cwist_https_accept()
cwist_error_t cwist_https_accept (cwist_https_context * ctx, int client_fd, cwist_https_connection ** conn)
Wrap an accepted TCP client socket in an OpenSSL connection object.
Parameters
ctx HTTPS context holding the configured SSL_CTX.
client_fd Accepted TCP socket descriptor.
conn Output pointer that receives the allocated connection wrapper.
Returns
Tagged CWIST error describing success or failure.
Definition at line 124 of file https.c.
cwist_https_close_connection()
void cwist_https_close_connection (cwist_https_connection * conn)
Gracefully close an HTTPS connection and free its buffers.
Parameters
conn HTTPS connection wrapper to close.
Definition at line 175 of file https.c.
cwist_https_destroy_context()
void cwist_https_destroy_context (cwist_https_context * ctx)
Free an HTTPS context and release its OpenSSL resources.
Parameters
ctx Context to destroy.
Definition at line 107 of file https.c.
cwist_https_init_context()
cwist_error_t cwist_https_init_context (cwist_https_context ** ctx, const char * cert_path, const char * key_path)
Initialize OpenSSL and create a server TLS context from PEM files.
Parameters
ctx Output pointer that receives the allocated HTTPS context.
cert_path Path to the PEM certificate chain.
key_path Path to the PEM private key.
Returns
Tagged CWIST error describing success or failure.
Definition at line 50 of file https.c.
cwist_https_receive_request()
cwist_http_request * cwist_https_receive_request (cwist_https_connection * conn)
Read from the TLS stream until a full HTTP request has been assembled.
Parameters
conn Active HTTPS connection wrapper.
Returns
Parsed HTTP request, or NULL on timeout, parse failure, or IO failure.
Definition at line 194 of file https.c.
References cwist_http_parse_request(), and cwist_http_request_destroy().
cwist_https_send_response()
cwist_error_t cwist_https_send_response (cwist_https_connection * conn, cwist_http_response * res)
Serialize an HTTP response and send it over an active TLS connection.
Parameters
conn Active HTTPS connection wrapper.
res Response object to serialize.
Returns
Tagged CWIST error describing success or failure.
Definition at line 299 of file https.c.
References cwist_http_stringify_response().
cwist_https_server_loop()
cwist_error_t cwist_https_server_loop (int server_fd, cwist_https_context * ctx, void(* handler)(cwist_https_connection *, void *), void * user_ctx)
Accept HTTPS clients in a loop and dispatch each one to the supplied handler.
Parameters
server_fd Bound listening socket descriptor.
ctx HTTPS context shared by all accepted connections.
handler Callback invoked for each successful TLS client wrapper.
user_ctx Opaque pointer forwarded to the handler.
Returns
Tagged CWIST error describing success or failure.
Definition at line 379 of file https.c.