cwist: include/cwist/net/http/http.h File Reference
http.h File Reference
HTTP Protocol Definitions and Helpers.
#include <cwist/core/sstring/sstring.h>
#include <cwist/sys/err/cwist_err.h>
#include <cwist/net/http/query.h>
#include <cwist/core/db/sql.h>
#include <cwist/sys/app/endpoint_opts.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/types.h>
Classes
struct cwist_http_header_node
Linked list node for request/response headers.
struct cwist_http_response
HTTP Response Object. Supports standard string body or Zero-Copy pointer body.
Macros
#define CWIST_HTTP_MAX_HEADER_SIZE (8 * 1024)
Typedefs
typedef enum cwist_http_method_t cwist_http_method_t
typedef struct cwist_http_header_node cwist_http_header_node
Linked list node for request/response headers.
typedef struct cwist_http_response cwist_http_response
HTTP Response Object. Supports standard string body or Zero-Copy pointer body.
Enumerations
enum cwist_http_method_t
Functions
cwist_error_t cwist_http_server_loop (int server_fd, cwist_server_config *config, void(*handler)(int, void *), void *ctx)
Run the main HTTP accept loop using the configured concurrency strategy.
int headers_have_content_length (cwist_http_header_node *headers)
Detect whether a header list already defines Content-Length.
Request Lifecycle
— API Functions —
cwist_http_request * cwist_http_request_create (void)
Allocate and initialize a default HTTP request object.
void cwist_http_request_destroy (cwist_http_request *req)
Destroy a parsed HTTP request and all nested allocations it owns.
cwist_http_request * cwist_http_parse_request (const char *raw_request)
Parse a raw HTTP request buffer into a CWIST request object.
cwist_http_request * cwist_http_receive_request (int client_fd, char *read_buf, size_t buf_size, size_t *buf_len)
Read from a client socket until a complete HTTP request is available.
Request Data Processing
cwist_sstring * cwist_get_client_ip_from_fd (int fd)
Resolve the peer IP address for a connected client socket.
Response Lifecycle
cwist_http_response * cwist_http_response_create (void)
Allocate and initialize a default HTTP response object.
void cwist_http_response_destroy (cwist_http_response *res)
Destroy an HTTP response and release any attached body resources.
void cwist_http_response_set_body_ptr (cwist_http_response *res, const void *ptr, size_t len)
Sets a direct pointer for the response body (Zero Copy). Use this when serving large files from memory mapped regions. The pointer must remain valid until the response is sent.
void cwist_http_response_set_body_ptr_managed (cwist_http_response *res, const void *ptr, size_t len, cwist_http_body_cleanup_fn cleanup, void *ctx)
Attach a managed zero-copy body pointer and optional cleanup hook to a response.
cwist_sstring * cwist_http_stringify_response (cwist_http_response *res)
Materialize an HTTP response into a contiguous string for debugging or TLS writes.
cwist_error_t cwist_http_send_response (int client_fd, cwist_http_response *res)
Serialize and send an HTTP response to a connected client socket.
cwist_error_t cwist_http_response_send_file (cwist_http_response *res, const char *file_path, const char *content_type_hint, size_t *out_size)
Prepare a response to serve a file either by buffering or direct streaming.
Header Manipulation
cwist_error_t cwist_http_header_add (cwist_http_header_node **head, const char *key, const char *value)
Prepend one header node to the linked-list header collection.
char * cwist_http_header_get (cwist_http_header_node *head, const char *key)
Finds a header value by key.
void cwist_http_header_free_all (cwist_http_header_node *head)
Destroy every node in a request or response header list.
Helpers
const char * cwist_http_method_to_string (cwist_http_method_t method)
Convert a HTTP method enum into its wire-format token.
cwist_http_method_t cwist_http_string_to_method (const char *method_str)
Parse a method token into CWIST's HTTP method enum.
TCP Socket Helpers
int cwist_make_socket_ipv4 (struct sockaddr_in *sockv4, const char *address, uint16_t port, uint16_t backlog)
Create an IPv4 socket and perform bind/listen.
cwist_error_t cwist_accept_socket (int server_fd, struct sockaddr *sockv4, void(*handler_func)(int client_fd, void *ctx), void *ctx)
Accept sockets and invoke a handler callback.
Detailed Description
HTTP Protocol Definitions and Helpers.
Definition in file http.h.
Macro Definition Documentation
CWIST_HTTP_MAX_HEADER_SIZE
#define CWIST_HTTP_MAX_HEADER_SIZE (8 * 1024)
— Constants and Limits —
Definition at line 47 of file http.h.
Referenced by cwist_http_send_response(), and cwist_http_stringify_response().
Typedef Documentation
cwist_http_header_node
typedef struct cwist_http_header_node cwist_http_header_node
Linked list node for request/response headers.
— Structures —
cwist_http_method_t
typedef enum cwist_http_method_t cwist_http_method_t
— Enums —
Enumeration Type Documentation
cwist_http_method_t
enum cwist_http_method_t
— Enums —
Definition at line 22 of file http.h.
Function Documentation
cwist_accept_socket()
cwist_error_t cwist_accept_socket (int server_fd, struct sockaddr * sockv4, void(* handler_func)(int client_fd, void *), void * ctx)
Accept sockets and invoke a handler callback.
Accept sockets and invoke a handler callback.
Parameters
server_fd Listening server socket.
sockv4 Scratch sockaddr buffer for accept(2).
handler_func Callback that handles one accepted client.
ctx Opaque callback context.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1155 of file http.c.
Referenced by cwist_http_server_loop().
cwist_get_client_ip_from_fd()
cwist_sstring * cwist_get_client_ip_from_fd (int fd)
Resolve the peer IP address for a connected client socket.
Parameters
fd Connected client socket descriptor.
Returns
Heap-allocated string containing the textual IP address.
Definition at line 235 of file http.c.
References cwist_sstring_create().
Referenced by cwist_mw_rate_limit_ip_handler().
cwist_http_header_add()
cwist_error_t cwist_http_header_add (cwist_http_header_node ** head, const char * key, const char * value)
Prepend one header node to the linked-list header collection.
Parameters
head Header-list head pointer to update.
key Header name to store.
value Header value to store.
Returns
Tagged CWIST error describing success or allocation failure.
Definition at line 91 of file http.c.
References cwist_sstring_create().
Referenced by cwist_http_parse_request(), cwist_http_response_send_file(), cwist_mw_cors_handler(), cwist_mw_jwt_auth_handler(), cwist_mw_rate_limit_ip_handler(), cwist_mw_request_id_handler(), and cwist_websocket_upgrade().
cwist_http_header_free_all()
void cwist_http_header_free_all (cwist_http_header_node * head)
Destroy every node in a request or response header list.
Parameters
head Head of the header linked list.
Definition at line 137 of file http.c.
Referenced by cwist_http_request_destroy(), and cwist_http_response_destroy().
cwist_http_header_get()
char * cwist_http_header_get (cwist_http_header_node * head, const char * key)
Finds a header value by key.
Returns
Raw C-string pointer (NULL if not found).
Finds a header value by key.
Parameters
head Head of the header linked list.
key Header name to search for.
Returns
Raw header value string, or NULL when absent.
Definition at line 122 of file http.c.
Referenced by cwist_http_response_send_file(), cwist_mw_access_log_handler(), cwist_mw_jwt_auth_handler(), cwist_mw_request_id_handler(), and cwist_websocket_upgrade().
cwist_http_method_to_string()
const char * cwist_http_method_to_string (cwist_http_method_t method)
Convert a HTTP method enum into its wire-format token.
Parameters
method HTTP method enum value.
Returns
Static string name for the method.
Definition at line 53 of file http.c.
Referenced by cwist_mw_access_log_handler().
cwist_http_parse_request()
cwist_http_request * cwist_http_parse_request (const char * raw_request)
Parse a raw HTTP request buffer into a CWIST request object.
Parameters
raw_request NUL-terminated request buffer containing headers and optional body.
Returns
Parsed request object, or NULL on malformed input.
Definition at line 621 of file http.c.
References cwist_http_header_add(), cwist_http_request_create(), cwist_http_request_destroy(), and cwist_http_string_to_method().
Referenced by cwist_http_receive_request(), and cwist_https_receive_request().
cwist_http_receive_request()
cwist_http_request * cwist_http_receive_request (int client_fd, char * read_buf, size_t buf_size, size_t * buf_len)
Read from a client socket until a complete HTTP request is available.
Parameters
client_fd Connected client socket descriptor.
read_buf Reusable receive buffer supplied by the caller.
buf_size Total capacity of read_buf.
buf_len In/out length of buffered leftover data.
Returns
Parsed request object, or NULL on timeout, parse failure, or IO failure.
Definition at line 740 of file http.c.
References cwist_http_parse_request(), and cwist_http_request_destroy().
cwist_http_request_create()
cwist_http_request * cwist_http_request_create (void)
Allocate and initialize a default HTTP request object.
Returns
Newly allocated request, or NULL on allocation failure.
Definition at line 200 of file http.c.
References CWIST_ENDPOINT_DEFAULT, cwist_query_map_create(), and cwist_sstring_create().
Referenced by cwist_http_parse_request().
cwist_http_request_destroy()
void cwist_http_request_destroy (cwist_http_request * req)
Destroy a parsed HTTP request and all nested allocations it owns.
Parameters
req Request object to destroy.
Definition at line 270 of file http.c.
References cwist_http_header_free_all().
Referenced by cwist_http_parse_request(), cwist_http_receive_request(), and cwist_https_receive_request().
cwist_http_response_create()
cwist_http_response * cwist_http_response_create (void)
Allocate and initialize a default HTTP response object.
Returns
Newly allocated response, or NULL on allocation failure.
Definition at line 321 of file http.c.
References CWIST_ENDPOINT_DEFAULT, cwist_sstring_create(), cwist_http_response::endpoint_opts, cwist_http_response::file_stream_auto_close, cwist_http_response::file_stream_fd, cwist_http_response::file_stream_len, cwist_http_response::file_stream_offset, cwist_http_response::is_ptr_body, cwist_http_response::ptr_body, cwist_http_response::ptr_body_cleanup, cwist_http_response::ptr_body_cleanup_ctx, cwist_http_response::ptr_body_len, cwist_http_response::status_text, cwist_http_response::use_file_stream, and cwist_http_response::version.
Referenced by cwist_websocket_upgrade().
cwist_http_response_destroy()
void cwist_http_response_destroy (cwist_http_response * res)
Destroy an HTTP response and release any attached body resources.
Parameters
res Response object to destroy.
Definition at line 354 of file http.c.
References cwist_http_header_free_all(), cwist_http_response::status_text, and cwist_http_response::version.
Referenced by cwist_websocket_upgrade().
cwist_http_response_send_file()
cwist_error_t cwist_http_response_send_file (cwist_http_response * res, const char * file_path, const char * content_type_hint, size_t * out_size)
Prepare a response to serve a file either by buffering or direct streaming.
Parameters
res Response object to populate.
file_path Filesystem path to the file that should be served.
content_type_hint Optional MIME type override.
out_size Optional output pointer receiving the file size in bytes.
Returns
Tagged CWIST error describing success or failure.
Definition at line 872 of file http.c.
References CWIST_ENDPOINT_FILE, cwist_http_header_add(), cwist_http_header_get(), cwist_http_response::endpoint_opts, cwist_http_response::file_stream_auto_close, cwist_http_response::file_stream_fd, cwist_http_response::file_stream_len, cwist_http_response::file_stream_offset, and cwist_http_response::use_file_stream.
cwist_http_response_set_body_ptr()
void cwist_http_response_set_body_ptr (cwist_http_response * res, const void * ptr, size_t len)
Sets a direct pointer for the response body (Zero Copy). Use this when serving large files from memory mapped regions. The pointer must remain valid until the response is sent.
Sets a direct pointer for the response body (Zero Copy). Use this when serving large files from memory mapped regions. The pointer must remain valid until the response is sent.
Parameters
res Response object to modify.
ptr External body pointer.
len Length of the external body in bytes.
Definition at line 372 of file http.c.
References cwist_http_response_set_body_ptr_managed().
cwist_http_response_set_body_ptr_managed()
void cwist_http_response_set_body_ptr_managed (cwist_http_response * res, const void * ptr, size_t len, cwist_http_body_cleanup_fn cleanup, void * ctx)
Attach a managed zero-copy body pointer and optional cleanup hook to a response.
Parameters
res Response object to modify.
ptr External body pointer.
len Length of the external body in bytes.
cleanup Optional cleanup callback for the body pointer.
ctx Opaque context forwarded to the cleanup callback.
Definition at line 384 of file http.c.
References cwist_http_response::is_ptr_body, cwist_http_response::ptr_body, cwist_http_response::ptr_body_cleanup, cwist_http_response::ptr_body_cleanup_ctx, and cwist_http_response::ptr_body_len.
Referenced by cwist_http_response_set_body_ptr().
cwist_http_send_response()
cwist_error_t cwist_http_send_response (int client_fd, cwist_http_response * res)
Serialize and send an HTTP response to a connected client socket.
Parameters
client_fd Connected client socket descriptor.
res Response object to send.
Returns
Tagged CWIST error describing success or transmission failure.
Definition at line 533 of file http.c.
References CWIST_HTTP_MAX_HEADER_SIZE, cwist_http_response::is_ptr_body, cwist_http_response::ptr_body, cwist_http_response::ptr_body_len, and cwist_http_response::use_file_stream.
Referenced by cwist_websocket_upgrade().
cwist_http_server_loop()
cwist_error_t cwist_http_server_loop (int server_fd, cwist_server_config * config, void(* handler)(int, void *), void * ctx)
Run the main HTTP accept loop using the configured concurrency strategy.
Parameters
server_fd Listening server socket.
config Server concurrency configuration flags.
handler Callback that handles one accepted client.
ctx Opaque callback context.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1191 of file http.c.
References cwist_accept_socket().
Referenced by cwist_app_listen().
cwist_http_string_to_method()
cwist_http_method_t cwist_http_string_to_method (const char * method_str)
Parse a method token into CWIST's HTTP method enum.
Parameters
method_str Raw method token from the request line.
Returns
Parsed enum value, or CWIST_HTTP_UNKNOWN when unsupported.
Definition at line 71 of file http.c.
Referenced by cwist_http_parse_request().
cwist_http_stringify_response()
cwist_sstring * cwist_http_stringify_response (cwist_http_response * res)
Materialize an HTTP response into a contiguous string for debugging or TLS writes.
Parameters
res Response object to stringify.
Returns
Heap-allocated response string, or NULL on invalid input.
Definition at line 601 of file http.c.
References CWIST_HTTP_MAX_HEADER_SIZE, cwist_sstring_create(), cwist_http_response::is_ptr_body, cwist_http_response::ptr_body, and cwist_http_response::ptr_body_len.
Referenced by cwist_https_send_response().
cwist_make_socket_ipv4()
int cwist_make_socket_ipv4 (struct sockaddr_in * sockv4, const char * address, uint16_t port, uint16_t backlog)
Create an IPv4 socket and perform bind/listen.
Create an IPv4 socket and perform bind/listen.
Parameters
sockv4 Output sockaddr structure populated for the bind call.
address IPv4 address string to bind.
port TCP port to listen on.
backlog Listen backlog passed to listen(2).
Returns
Listening socket fd on success, or a negative CWIST socket error code.
Definition at line 995 of file http.c.
Referenced by cwist_app_listen().
headers_have_content_length()
int headers_have_content_length (cwist_http_header_node * headers)
Detect whether a header list already defines Content-Length.
Parameters
headers Header linked list to scan.
Returns
1 when a Content-Length header is present, otherwise 0.
Definition at line 402 of file http.c.