cwist: src/core/sstring/sstring.c File Reference
sstring.c File Reference
Mutable string helpers used throughout CWIST for request/response and utility text handling.
#include <cwist/core/sstring/sstring.h>
#include <cwist/core/mem/alloc.h>
#include <cwist/sys/err/cwist_err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Functions
size_t cwist_sstring_get_size (cwist_sstring *str)
Forward declaration for the method-table size callback.
int cwist_sstring_compare_sstring (cwist_sstring *left, const cwist_sstring *right)
Forward declaration for the method-table compare callback.
cwist_error_t cwist_sstring_copy_sstring (cwist_sstring *origin, const cwist_sstring *from)
Forward declaration for the method-table copy callback.
cwist_error_t cwist_sstring_append_sstring (cwist_sstring *str, const cwist_sstring *from)
Forward declaration for the method-table append callback.
cwist_error_t cwist_sstring_append_sstring_escaped (cwist_sstring *str, const cwist_sstring *from)
Forward declaration for the escaped-append method-table callback.
cwist_error_t cwist_sstring_assign_len (cwist_sstring *str, const char *data, size_t len)
Replace the string contents with an arbitrary byte range.
cwist_error_t cwist_sstring_append_len (cwist_sstring *str, const char *data, size_t len)
Append an arbitrary byte range to the end of the string.
cwist_error_t cwist_sstring_init (cwist_sstring *str)
Initialize a mutable string with the default append/copy behavior.
cwist_error_t cwist_sstring_init_escaped (cwist_sstring *str)
Initialize a mutable string whose append helper performs HTML escaping.
cwist_error_t cwist_sstring_ltrim (cwist_sstring *str)
Trim leading ASCII whitespace from the string in place.
cwist_error_t cwist_sstring_rtrim (cwist_sstring *str)
Trim trailing ASCII whitespace from the string in place.
cwist_error_t cwist_sstring_trim (cwist_sstring *str)
Trim both leading and trailing ASCII whitespace from the string.
cwist_error_t cwist_sstring_change_size (cwist_sstring *str, size_t new_size, bool blow_data)
Resize the string buffer, optionally allowing truncation.
cwist_error_t cwist_sstring_assign (cwist_sstring *str, char *data)
Replace the string contents with a NUL-terminated C string.
cwist_error_t cwist_sstring_append (cwist_sstring *str, const char *data)
Append a NUL-terminated C string to the target string.
cwist_error_t cwist_sstring_append_escaped (cwist_sstring *str, const char *data)
Append a string while escaping a small HTML-sensitive character set.
cwist_error_t cwist_sstring_seek (cwist_sstring *str, char *substr, int location)
Copy a suffix of the string into a caller-provided buffer.
cwist_error_t cwist_sstring_copy (cwist_sstring *origin, char *destination)
Copy the entire string into a caller-provided destination buffer.
cwist_sstring * cwist_sstring_create (void)
Allocate and initialize a new heap-owned CWIST string object.
void cwist_sstring_destroy (cwist_sstring *str)
Destroy a heap-owned CWIST string and its backing buffer.
int cwist_sstring_compare (cwist_sstring *str, const char *compare_to)
Compare a CWIST string against a raw C string using strcmp semantics.
cwist_sstring * cwist_sstring_substr (cwist_sstring *str, int start, int length)
Create a heap-owned substring spanning the requested range.
Detailed Description
Mutable string helpers used throughout CWIST for request/response and utility text handling.
Definition in file sstring.c.
Function Documentation
cwist_sstring_append()
cwist_error_t cwist_sstring_append (cwist_sstring * str, const char * data)
Append a NUL-terminated C string to the target string.
Parameters
str Target string object.
data Source string to append.
Returns
ERR_SSTRING_OKAY on success, or an error payload describing the failure.
Definition at line 339 of file sstring.c.
Referenced by cwist_sstring_append_sstring().
cwist_sstring_append_escaped()
cwist_error_t cwist_sstring_append_escaped (cwist_sstring * str, const char * data)
Append a string while escaping a small HTML-sensitive character set.
Parameters
str Target string object.
data Source string to append in escaped form.
Returns
ERR_SSTRING_OKAY on success, or an error payload describing the failure.
Definition at line 393 of file sstring.c.
Referenced by cwist_sstring_append_sstring_escaped().
cwist_sstring_append_len()
cwist_error_t cwist_sstring_append_len (cwist_sstring * str, const char * data, size_t len)
Append an arbitrary byte range to the end of the string.
Parameters
str Target string object.
data Source bytes to append.
len Number of source bytes to append.
Returns
ERR_SSTRING_OKAY on success, or an error payload describing the failure.
Definition at line 63 of file sstring.c.
cwist_sstring_append_sstring()
cwist_error_t cwist_sstring_append_sstring (cwist_sstring * str, const cwist_sstring * from)
Forward declaration for the method-table append callback.
Append the contents of one CWIST string onto another.
Parameters
str Destination string.
from Source CWIST string.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid input.
Definition at line 472 of file sstring.c.
References cwist_sstring_append().
cwist_sstring_append_sstring_escaped()
cwist_error_t cwist_sstring_append_sstring_escaped (cwist_sstring * str, const cwist_sstring * from)
Forward declaration for the escaped-append method-table callback.
Append one CWIST string to another while escaping HTML-sensitive characters.
Parameters
str Destination string.
from Source CWIST string.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid input.
Definition at line 492 of file sstring.c.
References cwist_sstring_append_escaped().
cwist_sstring_assign()
cwist_error_t cwist_sstring_assign (cwist_sstring * str, char * data)
Replace the string contents with a NUL-terminated C string.
Parameters
str Target string object.
data Source string, or NULL to clear the value.
Returns
ERR_SSTRING_OKAY on success, or an error payload describing the failure.
Definition at line 289 of file sstring.c.
References cwist_sstring_change_size().
Referenced by cwist_sstring_copy_sstring().
cwist_sstring_assign_len()
cwist_error_t cwist_sstring_assign_len (cwist_sstring * str, const char * data, size_t len)
Replace the string contents with an arbitrary byte range.
Parameters
str Target string object.
data Source bytes to copy.
len Number of source bytes to copy.
Returns
ERR_SSTRING_OKAY on success, or an error payload describing the failure.
Definition at line 32 of file sstring.c.
cwist_sstring_change_size()
cwist_error_t cwist_sstring_change_size (cwist_sstring * str, size_t new_size, bool blow_data)
Resize the string buffer, optionally allowing truncation.
Parameters
str String object to resize.
new_size Requested new size in bytes.
blow_data When true, allow shrinking below the current content length.
Returns
ERR_SSTRING_OKAY on success, or an error describing the resize failure.
Definition at line 239 of file sstring.c.
Referenced by cwist_sstring_assign().
cwist_sstring_compare()
int cwist_sstring_compare (cwist_sstring * str, const char * compare_to)
Compare a CWIST string against a raw C string using strcmp semantics.
Parameters
str Left-hand CWIST string.
compare_to Right-hand raw C string.
Returns
Negative, zero, or positive depending on lexical ordering.
Definition at line 607 of file sstring.c.
cwist_sstring_compare_sstring()
int cwist_sstring_compare_sstring (cwist_sstring * left, const cwist_sstring * right)
Forward declaration for the method-table compare callback.
Compare two CWIST string objects using strcmp semantics.
Parameters
left Left-hand string.
right Right-hand string.
Returns
Negative, zero, or positive depending on lexical ordering.
Definition at line 158 of file sstring.c.
cwist_sstring_copy()
cwist_error_t cwist_sstring_copy (cwist_sstring * origin, char * destination)
Copy the entire string into a caller-provided destination buffer.
Parameters
origin Source string object.
destination Destination C buffer.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid input.
Definition at line 538 of file sstring.c.
cwist_sstring_copy_sstring()
cwist_error_t cwist_sstring_copy_sstring (cwist_sstring * origin, const cwist_sstring * from)
Forward declaration for the method-table copy callback.
Copy one CWIST string into another.
Parameters
origin Destination string object.
from Source string object, or NULL to clear the destination.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid input.
Definition at line 558 of file sstring.c.
References cwist_sstring_assign().
cwist_sstring_create()
cwist_sstring * cwist_sstring_create (void)
Allocate and initialize a new heap-owned CWIST string object.
Returns
Newly allocated string object, or NULL on allocation failure.
Definition at line 574 of file sstring.c.
Referenced by cwist_get_client_ip_from_fd(), cwist_html_element_add_class(), cwist_html_element_create(), cwist_html_element_set_text(), cwist_html_render(), cwist_http_header_add(), cwist_http_request_create(), cwist_http_response_create(), cwist_http_stringify_response(), cwist_json_builder_create(), cwist_mux_handle(), and cwist_sstring_substr().
cwist_sstring_destroy()
void cwist_sstring_destroy (cwist_sstring * str)
Destroy a heap-owned CWIST string and its backing buffer.
Parameters
str String object to destroy.
Definition at line 594 of file sstring.c.
Referenced by cwist_sstring_substr().
cwist_sstring_get_size()
size_t cwist_sstring_get_size (cwist_sstring * str)
Forward declaration for the method-table size callback.
Return the cached string size in bytes.
Parameters
str String object to inspect.
Returns
Stored size, or 0 when the string is NULL.
Definition at line 148 of file sstring.c.
cwist_sstring_init()
cwist_error_t cwist_sstring_init (cwist_sstring * str)
Initialize a mutable string with the default append/copy behavior.
Parameters
str String object to initialize in caller-owned storage.
Returns
ERR_SSTRING_OKAY on success, or ERR_SSTRING_NULL_STRING for NULL input.
Definition at line 100 of file sstring.c.
cwist_sstring_init_escaped()
cwist_error_t cwist_sstring_init_escaped (cwist_sstring * str)
Initialize a mutable string whose append helper performs HTML escaping.
Parameters
str String object to initialize in caller-owned storage.
Returns
ERR_SSTRING_OKAY on success, or ERR_SSTRING_NULL_STRING for NULL input.
Definition at line 124 of file sstring.c.
cwist_sstring_ltrim()
cwist_error_t cwist_sstring_ltrim (cwist_sstring * str)
Trim leading ASCII whitespace from the string in place.
Parameters
str String object to mutate.
Returns
ERR_SSTRING_OKAY on success, or ERR_SSTRING_NULL_STRING for invalid input.
Definition at line 172 of file sstring.c.
Referenced by cwist_sstring_trim().
cwist_sstring_rtrim()
cwist_error_t cwist_sstring_rtrim (cwist_sstring * str)
Trim trailing ASCII whitespace from the string in place.
Parameters
str String object to mutate.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid input.
Definition at line 197 of file sstring.c.
Referenced by cwist_sstring_trim().
cwist_sstring_seek()
cwist_error_t cwist_sstring_seek (cwist_sstring * str, char * substr, int location)
Copy a suffix of the string into a caller-provided buffer.
Parameters
str Source string object.
substr Destination C buffer.
location Starting offset inside the source string.
Returns
ERR_SSTRING_OKAY on success, or an error describing invalid bounds/input.
Definition at line 513 of file sstring.c.
cwist_sstring_substr()
cwist_sstring * cwist_sstring_substr (cwist_sstring * str, int start, int length)
Create a heap-owned substring spanning the requested range.
Parameters
str Source string object.
start Zero-based starting index.
length Requested substring length.
Returns
Newly allocated substring, or NULL when the range is invalid or OOM occurs.
Definition at line 624 of file sstring.c.
References cwist_sstring_create(), and cwist_sstring_destroy().
cwist_sstring_trim()
cwist_error_t cwist_sstring_trim (cwist_sstring * str)
Trim both leading and trailing ASCII whitespace from the string.
Parameters
str String object to mutate.
Returns
ERR_SSTRING_OKAY on success, or the first trim error encountered.
Definition at line 226 of file sstring.c.
References cwist_sstring_ltrim(), and cwist_sstring_rtrim().