cwist: include/cwist/sys/app/app.h File Reference
app.h File Reference
Core Application Structure and Lifecycle Management.
#include <cwist/net/http/http.h>
#include <cwist/net/http/https.h>
#include <cwist/core/db/sql.h>
#include <cwist/sys/err/cwist_err.h>
#include <cwist/core/macros.h>
#include <cwist/sys/app/big_dumb_reply.h>
#include <ttak/mem_tree/mem_tree.h>
#include <cwist/net/websocket/websocket.h>
Classes
struct cwist_middleware_node
Linked list node for middleware chain.
struct cwist_app
Main Application Context.
struct cwist_file_t
Represents a file loaded into the fixed memory pool.
struct cwist_fix_server_mem
Fixed Server Memory Manager.
Typedefs
typedef void(* cwist_handler_func) (cwist_http_request *req, cwist_http_response *res)
Function pointer type for HTTP route handlers.
typedef void(* cwist_ws_handler_func) (cwist_websocket *ws)
Function pointer type for WebSocket handlers.
typedef void(* cwist_error_handler_func) (cwist_http_request *req, cwist_http_response *res, cwist_http_status_t status)
Function pointer type for error handlers.
typedef void(* cwist_middleware_func) (cwist_http_request *req, cwist_http_response *res, cwist_handler_func next)
Middleware type that receives req/res pair and the next stage in the chain.
typedef struct cwist_middleware_node cwist_middleware_node
Linked list node for middleware chain.
typedef struct cwist_app cwist_app
Main Application Context.
typedef struct cwist_file_t cwist_file_t
Represents a file loaded into the fixed memory pool.
typedef struct cwist_fix_server_mem cwist_fix_server_mem
Fixed Server Memory Manager.
Functions
cwist_app * cwist_app_create (void)
Creates a new CWIST application instance.
void cwist_app_destroy (cwist_app *app)
Destroys the application and frees all resources.
void cwist_app_set_max_memspace (cwist_app *app, size_t size)
Sets the maximum memory space for the static file pool.
void cwist_app_configure_bdr (cwist_app *app, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Configures the Big Dumb Reply guardrails.
cwist_error_t cwist_app_use_https (cwist_app *app, const char *cert_path, const char *key_path)
Enable TLS for the application using the supplied certificate pair.
cwist_error_t cwist_app_use_db (cwist_app *app, const char *db_path)
Open a SQLite database and attach it as the shared application handle.
cwist_error_t cwist_app_use_nuke_db (cwist_app *app, const char *db_path, int sync_interval_ms)
Enable NUKE DB and fall back to standard SQLite when RAM bootstrap fails.
cwist_db * cwist_app_get_db (cwist_app *app)
Return the active shared database wrapper for the application.
Middleware
void cwist_app_use (cwist_app *app, cwist_middleware_func mw)
Append a middleware callback to the application's execution chain.
Error Handling Configuration
void cwist_app_set_error_handler (cwist_app *app, cwist_error_handler_func handler)
Install a custom HTTP error callback.
Routing
void cwist_app_get (cwist_app *app, const char *path, cwist_handler_func handler)
Registers a GET route handler.
void cwist_app_post (cwist_app *app, const char *path, cwist_handler_func handler)
Register a POST handler with default endpoint options.
void cwist_app_ws (cwist_app *app, const char *path, cwist_ws_handler_func handler)
Register a WebSocket upgrade endpoint with default options.
void cwist_app_get_opt (cwist_app *app, const char *path, cwist_handler_func handler, cwist_endpoint_opt_t opts)
Register a GET handler with explicit endpoint options.
void cwist_app_post_opt (cwist_app *app, const char *path, cwist_handler_func handler, cwist_endpoint_opt_t opts)
Register a POST handler with explicit endpoint options.
void cwist_app_ws_opt (cwist_app *app, const char *path, cwist_ws_handler_func handler, cwist_endpoint_opt_t opts)
Register a WebSocket route with explicit endpoint options.
cwist_error_t cwist_app_static (cwist_app *app, const char *url_prefix, const char *directory)
Serves a directory of static files at a URL prefix. Files are loaded into the fixed memory pool for Zero-Copy serving.
Startup
int cwist_app_listen (cwist_app *app, int port)
Initialize runtime services and enter the HTTP or HTTPS server loop.
Detailed Description
Core Application Structure and Lifecycle Management.
Definition in file app.h.
Typedef Documentation
cwist_app
typedef struct cwist_app cwist_app
Main Application Context.
Manages routing, middleware, database connections, memory pools, and caching strategies (BDR).
cwist_file_t
typedef struct cwist_file_t cwist_file_t
Represents a file loaded into the fixed memory pool.
— Memory Management —
cwist_fix_server_mem
typedef struct cwist_fix_server_mem cwist_fix_server_mem
Fixed Server Memory Manager.
Pre-allocates a large contiguous block of memory to serve static files via Zero-Copy pointer passing. Supports hot-reloading on file change.
cwist_handler_func
typedef void(* cwist_handler_func) (cwist_http_request *req, cwist_http_response *res)
Function pointer type for HTTP route handlers.
Parameters
req Pointer to the HTTP request object.
res Pointer to the HTTP response object.
Definition at line 24 of file app.h.
cwist_ws_handler_func
typedef void(* cwist_ws_handler_func) (cwist_websocket *ws)
Function pointer type for WebSocket handlers.
Parameters
ws Pointer to the WebSocket context.
Definition at line 30 of file app.h.
Function Documentation
cwist_app_configure_bdr()
void cwist_app_configure_bdr (cwist_app * app, size_t max_bytes, time_t max_entry_age_sec, uint64_t revalidate_hits)
Configures the Big Dumb Reply guardrails.
Parameters
app Target app.
max_bytes Maximum bytes to keep in RAM (0 = keep default).
max_entry_age_sec Retire cached replies older than this (<=0 keeps default).
revalidate_hits Force refresh after this many hits (0 = keep default).
Configures the Big Dumb Reply guardrails.
Parameters
app Application whose BDR context should be tuned.
max_bytes Maximum total cache footprint.
max_entry_age_sec Maximum age for cached entries.
revalidate_hits Hit count that forces revalidation.
Definition at line 902 of file app.c.
References cwist_app::bdr_ctx, and cwist_bdr_set_limits().
cwist_app_create()
cwist_app * cwist_app_create (void)
Creates a new CWIST application instance.
— API —
Returns
Pointer to the allocated app, or NULL on failure.
Creates a new CWIST application instance.
Returns
Newly created application, or NULL when allocation fails.
Definition at line 830 of file app.c.
References cwist_app::bdr_ctx, cwist_bdr_create(), cwist_app::db, cwist_app::db_path, cwist_app::error_handler, cwist_app::max_mem_space, cwist_app::mem_manager, cwist_app::middlewares, cwist_app::nuke_enabled, cwist_app::router, cwist_app::ssl_ctx, and cwist_app::static_dirs.
cwist_app_destroy()
void cwist_app_destroy (cwist_app * app)
Destroys the application and frees all resources.
Parameters
app Pointer to the app to destroy.
Destroys the application and frees all resources.
Parameters
app Application instance to destroy.
Definition at line 911 of file app.c.
References cwist_app::bdr_ctx, cwist_bdr_destroy(), cwist_nuke_close(), cwist_app::db, cwist_app::db_path, cwist_fix_server_mem::file_tree, cwist_fix_server_mem::files, cwist_file_t::fs_path, cwist_app::mem_manager, cwist_app::middlewares, cwist_file_t::node, cwist_app::nuke_enabled, cwist_file_t::path, cwist_app::router, cwist_app::ssl_ctx, and cwist_app::static_dirs.
cwist_app_get()
void cwist_app_get (cwist_app * app, const char * path, cwist_handler_func handler)
Registers a GET route handler.
Registers a GET route handler.
Parameters
app Application being configured.
path Exact route path.
handler HTTP handler invoked for matching requests.
Definition at line 1205 of file app.c.
References CWIST_ENDPOINT_DEFAULT.
cwist_app_get_db()
cwist_db * cwist_app_get_db (cwist_app * app)
Return the active shared database wrapper for the application.
Parameters
app Application whose database handle should be queried.
Returns
Database wrapper, or NULL when no database is configured.
Definition at line 1135 of file app.c.
References cwist_nuke_get_db(), cwist_app::db, and cwist_app::nuke_enabled.
cwist_app_get_opt()
void cwist_app_get_opt (cwist_app * app, const char * path, cwist_handler_func handler, cwist_endpoint_opt_t opts)
Register a GET handler with explicit endpoint options.
Parameters
app Application being configured.
path Exact route path.
handler HTTP handler invoked for matching requests.
opts Endpoint flags controlling cache and transport behavior.
Definition at line 1237 of file app.c.
cwist_app_listen()
int cwist_app_listen (cwist_app * app, int port)
Initialize runtime services and enter the HTTP or HTTPS server loop.
Parameters
app Application instance to run.
port TCP port to bind.
Returns
0 on success, or -1 when initialization or bind fails.
Definition at line 1464 of file app.c.
References cwist_http_server_loop(), cwist_make_socket_ipv4(), cwist_app::mem_manager, and cwist_app::ssl_ctx.
cwist_app_post()
void cwist_app_post (cwist_app * app, const char * path, cwist_handler_func handler)
Register a POST handler with default endpoint options.
Parameters
app Application being configured.
path Exact route path.
handler HTTP handler invoked for matching requests.
Definition at line 1215 of file app.c.
References CWIST_ENDPOINT_DEFAULT.
cwist_app_post_opt()
void cwist_app_post_opt (cwist_app * app, const char * path, cwist_handler_func handler, cwist_endpoint_opt_t opts)
Register a POST handler with explicit endpoint options.
Parameters
app Application being configured.
path Exact route path.
handler HTTP handler invoked for matching requests.
opts Endpoint flags controlling cache and transport behavior.
Definition at line 1248 of file app.c.
cwist_app_set_error_handler()
void cwist_app_set_error_handler (cwist_app * app, cwist_error_handler_func handler)
Install a custom HTTP error callback.
Parameters
app Application being configured.
handler Handler invoked for framework-generated errors such as 404 responses.
Definition at line 891 of file app.c.
References cwist_app::error_handler.
cwist_app_set_max_memspace()
void cwist_app_set_max_memspace (cwist_app * app, size_t size)
Sets the maximum memory space for the static file pool.
Parameters
app Pointer to the app.
size Size in bytes (Use macros like CWIST_MIB(64)).
Sets the maximum memory space for the static file pool.
Parameters
app Application being configured.
size Maximum bytes reserved for static payload caching.
Definition at line 882 of file app.c.
References cwist_app::max_mem_space.
cwist_app_static()
cwist_error_t cwist_app_static (cwist_app * app, const char * url_prefix, const char * directory)
Serves a directory of static files at a URL prefix. Files are loaded into the fixed memory pool for Zero-Copy serving.
Parameters
app Pointer to the app.
url_prefix URL prefix (e.g., "/static").
directory Local filesystem path.
Note
Additional method helpers can be added as needed.
Serves a directory of static files at a URL prefix. Files are loaded into the fixed memory pool for Zero-Copy serving.
Parameters
app Application being configured.
url_prefix Request-path prefix such as "/static".
directory Filesystem directory that backs the mapping.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1150 of file app.c.
References cwist_app::static_dirs.
cwist_app_use()
void cwist_app_use (cwist_app * app, cwist_middleware_func mw)
Append a middleware callback to the application's execution chain.
Parameters
app Application being configured.
mw Middleware callback to append.
Definition at line 862 of file app.c.
References cwist_app::middlewares.
cwist_app_use_db()
cwist_error_t cwist_app_use_db (cwist_app * app, const char * db_path)
Open a SQLite database and attach it as the shared application handle.
Parameters
app Application being configured.
db_path Filesystem path or SQLite URI to open.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1051 of file app.c.
References cwist_app::db, cwist_app::db_path, and cwist_app::nuke_enabled.
Referenced by cwist_app_use_nuke_db().
cwist_app_use_https()
cwist_error_t cwist_app_use_https (cwist_app * app, const char * cert_path, const char * key_path)
Enable TLS for the application using the supplied certificate pair.
Parameters
app Application being configured.
cert_path PEM certificate chain path.
key_path PEM private key path.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1031 of file app.c.
References cwist_app::ssl_ctx.
cwist_app_use_nuke_db()
cwist_error_t cwist_app_use_nuke_db (cwist_app * app, const char * db_path, int sync_interval_ms)
Enable NUKE DB and fall back to standard SQLite when RAM bootstrap fails.
Parameters
app Application being configured.
db_path On-disk database file to mirror into memory.
sync_interval_ms Synchronization interval forwarded to NUKE DB.
Returns
Tagged CWIST error describing success or failure.
Definition at line 1084 of file app.c.
References cwist_app_use_db(), cwist_nuke_close(), cwist_nuke_get_db(), cwist_nuke_init(), CWIST_NUKE_OK, cwist_app::db, cwist_app::db_path, and cwist_app::nuke_enabled.
cwist_app_ws()
void cwist_app_ws (cwist_app * app, const char * path, cwist_ws_handler_func handler)
Register a WebSocket upgrade endpoint with default options.
Parameters
app Application being configured.
path Exact GET route that should upgrade to WebSocket.
handler WebSocket handler invoked after a successful upgrade.
Definition at line 1225 of file app.c.
References CWIST_ENDPOINT_DEFAULT, and cwist_app::router.
cwist_app_ws_opt()
void cwist_app_ws_opt (cwist_app * app, const char * path, cwist_ws_handler_func handler, cwist_endpoint_opt_t opts)
Register a WebSocket route with explicit endpoint options.
Parameters
app Application being configured.
path Exact GET route that should upgrade to WebSocket.
handler WebSocket handler invoked after a successful upgrade.
opts Endpoint flags associated with the route.
Definition at line 1259 of file app.c.
References CWIST_ENDPOINT_DEFAULT, and cwist_app::router.