cwist: include/cwist/sys/session/session_manager.h File Reference
session_manager.h File Reference
Request-scoped arena and shared-payload helpers for session data.
#include <stddef.h>
#include <stdint.h>
Classes
struct session_rc_header
Reference-count header placed immediately before shared session payloads.
struct session_arena
Linear arena used for fast request-lifetime allocations.
struct session_manager
Top-level session allocator state owned by a request context.
Functions
void session_arena_init (struct session_arena *arena, uint8_t *buffer, size_t capacity)
Bind a caller-owned buffer to a session arena and reset its cursor.
void * session_arena_alloc (struct session_arena *arena, size_t size)
Allocate aligned storage from the request arena.
void session_arena_reset (struct session_arena *arena)
Reset the request arena so future allocations reuse the full buffer.
void session_rc_init (struct session_rc_header *header, void(*destructor)(void *))
Initialize the metadata that tracks a shared session allocation.
void * session_shared_alloc (size_t payload_size, void(*destructor)(void *))
Allocate a zeroed payload preceded by a reference-count header.
void session_shared_inc (void *payload)
Increment the reference count for a shared payload.
void session_shared_dec (void *payload)
Decrement the reference count and free the payload when it reaches zero.
void session_manager_init (struct session_manager *manager, uint8_t *buffer, size_t capacity)
Initialize a session manager around a caller-supplied arena buffer.
void session_manager_reset (struct session_manager *manager)
Reset all request-scoped allocations owned by the manager.
Detailed Description
Request-scoped arena and shared-payload helpers for session data.
Definition in file session_manager.h.
Function Documentation
session_arena_alloc()
void * session_arena_alloc (struct session_arena * arena, size_t size)
Allocate aligned storage from the request arena.
Parameters
arena Arena to allocate from.
size Requested payload size in bytes.
Returns
Pointer to the reserved range, or NULL when capacity is exhausted.
Allocate aligned storage from the request arena.
Parameters
arena Arena that owns the backing storage.
size Number of bytes requested before alignment.
Returns
Pointer to a contiguous region, or NULL when the arena is exhausted.
Definition at line 30 of file session_manager.c.
session_arena_init()
void session_arena_init (struct session_arena * arena, uint8_t * buffer, size_t capacity)
Bind a caller-owned buffer to a session arena and reset its cursor.
Parameters
arena Arena to initialize.
buffer Backing storage owned by the caller.
capacity Size of buffer in bytes.
Bind a caller-owned buffer to a session arena and reset its cursor.
Parameters
arena Arena to initialize.
buffer Backing storage to consume sequentially.
capacity Total number of bytes available in buffer.
Definition at line 17 of file session_manager.c.
Referenced by session_manager_init().
session_arena_reset()
void session_arena_reset (struct session_arena * arena)
Reset the request arena so future allocations reuse the full buffer.
Parameters
arena Arena to reset.
Reset the request arena so future allocations reuse the full buffer.
Parameters
arena Arena to reset.
Definition at line 45 of file session_manager.c.
Referenced by session_manager_reset().
session_manager_init()
void session_manager_init (struct session_manager * manager, uint8_t * buffer, size_t capacity)
Initialize a session manager around a caller-supplied arena buffer.
Parameters
manager Session manager to initialize.
buffer Buffer used for request-scoped arena allocations.
capacity Size of buffer in bytes.
Initialize a session manager around a caller-supplied arena buffer.
Parameters
manager Manager to initialize.
buffer Backing arena storage.
capacity Size of buffer in bytes.
Definition at line 111 of file session_manager.c.
References session_arena_init().
session_manager_reset()
void session_manager_reset (struct session_manager * manager)
Reset all request-scoped allocations owned by the manager.
Parameters
manager Session manager to reset.
manager Manager whose arena should be rewound.
Definition at line 120 of file session_manager.c.
References session_arena_reset().
session_rc_init()
void session_rc_init (struct session_rc_header * header, void(* destructor)(void *))
Initialize the metadata that tracks a shared session allocation.
Parameters
header Header to initialize.
destructor Optional destructor invoked before the payload is freed.
Initialize the metadata that tracks a shared session allocation.
Parameters
header Header that precedes the payload.
destructor Optional callback run just before the payload is freed.
Definition at line 55 of file session_manager.c.
Referenced by session_shared_alloc().
session_shared_alloc()
void * session_shared_alloc (size_t payload_size, void(* destructor)(void *))
Allocate a zeroed payload preceded by a reference-count header.
Parameters
payload_size Number of bytes to expose to the caller.
destructor Optional destructor for the payload.
Returns
Pointer to the payload region, or NULL when allocation fails.
Allocate a zeroed payload preceded by a reference-count header.
Parameters
payload_size Number of bytes visible to callers.
destructor Optional callback invoked before memory is released.
Returns
Zeroed payload pointer, or NULL when allocation fails.
Definition at line 67 of file session_manager.c.
References session_rc_init().
session_shared_dec()
void session_shared_dec (void * payload)
Decrement the reference count and free the payload when it reaches zero.
Parameters
payload Payload returned by session_shared_alloc().
Decrement the reference count and free the payload when it reaches zero.
Parameters
payload Payload returned by session_shared_alloc().
Definition at line 92 of file session_manager.c.
session_shared_inc()
void session_shared_inc (void * payload)
Increment the reference count for a shared payload.
Parameters
payload Payload returned by session_shared_alloc().
Definition at line 82 of file session_manager.c.