cwist: include/cwist/core/utils/json_heal.h File Reference
json_heal.h File Reference
Self-Healing JSON Recovery Layer (CWIST)
#include <stdbool.h>
#include <stddef.h>
#include <cjson/cJSON.h>
Classes
struct cwist_schema_field
Single field descriptor used by both the healer and the Zod validator.
struct cwist_schema
A complete schema: array of field descriptors + count.
struct cwist_heal_config
Configuration passed to cwist_json_heal().
struct cwist_heal_result
Result of a healing attempt.
Typedefs
typedef struct cwist_schema_field cwist_schema_field_t
Single field descriptor used by both the healer and the Zod validator.
typedef struct cwist_schema cwist_schema_t
A complete schema: array of field descriptors + count.
typedef char *(* cwist_sllm_heal_fn) (const char *broken_json, const cwist_schema_t *schema, void *userdata)
Optional deep-recovery callback (e.g. backed by an LLM).
typedef struct cwist_heal_config cwist_heal_config_t
Configuration passed to cwist_json_heal().
typedef struct cwist_heal_result cwist_heal_result_t
Result of a healing attempt.
Enumerations
enum cwist_field_type_t
Expected value type for a schema field.
Functions
cwist_heal_result_t cwist_json_heal (const char *input, const cwist_heal_config_t *cfg)
Attempt to heal a potentially broken JSON string.
int cwist_json_schema_align (cJSON *obj, const cwist_schema_t *schema, char *log, size_t log_sz)
Apply L2 schema alignment to an already-parsed cJSON object in place.
void cwist_heal_result_free (cwist_heal_result_t *r)
Free resources owned by a cwist_heal_result_t.
Detailed Description
Self-Healing JSON Recovery Layer (CWIST)
Three-tier recovery pipeline: L1 – Syntax : fast fixes (BOM, line-comments, trailing commas, bracket balancing) L2 – Schema : field-name alias resolution + type coercion against a known schema L3 – SLLM : user-supplied deep-recovery callback (AI / LLM inference)
Usage:
static const cwist_schema_field_t fields[] = {
    { "user_id", {"userId", "uid", NULL}, CWIST_FIELD_INT,    true  },
    { "name",    {NULL},                  CWIST_FIELD_STRING, true  },
    { "active",  {"is_active", NULL},     CWIST_FIELD_BOOL,   false },
};
static const cwist_schema_t schema = { fields, 3 };
cwist_heal_config_t cfg = { .threshold = 0.8, .schema = &schema };
cwist_heal_result_t r   = cwist_json_heal(broken_input, &cfg);
if (r.json) {
    printf("healed(%d): %s\n  log: %s\n", r.level, r.json, r.log);
}
cwist_heal_result_free(&r);
Definition in file json_heal.h.
Typedef Documentation
cwist_schema_field_t
typedef struct cwist_schema_field cwist_schema_field_t
Single field descriptor used by both the healer and the Zod validator.
aliases is a NULL-terminated list of alternative names that will be renamed to name during L2 alignment. Fuzzy (case-insensitive, separator-stripped) matching is applied when exact aliases do not match.
cwist_sllm_heal_fn
typedef char *(* cwist_sllm_heal_fn) (const char *broken_json, const cwist_schema_t *schema, void *userdata)
Optional deep-recovery callback (e.g. backed by an LLM).
Called only when L1 and L2 both fail to produce valid JSON. Must return a heap-allocated (plain malloc) JSON string, or NULL on failure. The caller will free the returned string with free(). The callback MUST use the standard C malloc allocator (not cwist_alloc) so that the framework can release it with free().
Parameters
broken_json The damaged input string.
schema Schema hint (may be NULL).
userdata Opaque pointer from cwist_heal_config_t.
Returns
Heap-allocated recovered JSON string, or NULL.
Definition at line 89 of file json_heal.h.
Function Documentation
cwist_heal_result_free()
void cwist_heal_result_free (cwist_heal_result_t * r)
Free resources owned by a cwist_heal_result_t.
Free resources owned by a cwist_heal_result_t.
Parameters
r Result object previously populated by cwist_json_heal().
Definition at line 452 of file json_heal.c.
References cwist_heal_result::json.
Referenced by cwist_db_insert_healed().
cwist_json_heal()
cwist_heal_result_t cwist_json_heal (const char * input, const cwist_heal_config_t * cfg)
Attempt to heal a potentially broken JSON string.
Tries L1 → L2 → L3 in order, stopping at the first successful parse whose confidence meets the threshold. If the input is already valid JSON it is returned verbatim (healed=false), though L2 alignment is still applied when a schema is provided.
Parameters
input Raw (possibly broken) JSON string.
cfg Healing configuration (may be NULL for defaults).
Returns
Heap-allocated result; caller must call cwist_heal_result_free().
Attempt to heal a potentially broken JSON string.
The function first attempts a direct parse, then falls back to the internal L1 syntax healer, and finally consults the user-provided SLLM callback when configured. Each successful step records the recovery level, confidence, and a short operator-facing log of the transformations that were applied.
Parameters
input Raw JSON text that may contain structural defects.
cfg Optional recovery configuration. NULL applies the built-in defaults.
Returns
Result structure describing the best recovery path that succeeded.
Definition at line 375 of file json_heal.c.
References cwist_heal_result::confidence, cwist_json_schema_align(), cwist_heal_result::healed, cwist_heal_result::json, cwist_heal_result::level, cwist_heal_result::log, cwist_heal_config::schema, cwist_heal_config::sllm_fn, cwist_heal_config::sllm_userdata, and cwist_heal_config::threshold.
Referenced by cwist_db_insert_healed().
cwist_json_schema_align()
int cwist_json_schema_align (cJSON * obj, const cwist_schema_t * schema, char * log, size_t log_sz)
Apply L2 schema alignment to an already-parsed cJSON object in place.
Renames aliased / fuzzy-matched field names to their canonical forms and coerces mismatched types (e.g. "123" → 123 for an INT field).
Parameters
obj cJSON object to modify in place.
schema Schema descriptor.
log Optional output buffer for change description.
log_sz Size of log buffer.
Returns
Number of fields modified, or -1 on error.
Definition at line 230 of file json_heal.c.
References cwist_schema_field::aliases, cwist_schema_field::name, and cwist_schema_field::type.
Referenced by cwist_json_heal().