cwist: src/core/html/builder.c File Reference
builder.c File Reference
Minimal HTML tree construction and rendering helpers.
#include <cwist/core/html/builder.h>
#include <cwist/core/sstring/sstring.h>
#include <cwist/core/mem/alloc.h>
#include <cjson/cJSON.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Functions
cwist_html_element_t * cwist_html_element_create (const char *tag)
Allocate a new HTML element node for the supplied tag name.
void cwist_html_element_destroy (cwist_html_element_t *el)
Recursively destroy an element and every descendant it owns.
void cwist_html_element_add_attr (cwist_html_element_t *el, const char *key, const char *value)
Insert or replace an HTML attribute on an element.
void cwist_html_element_set_id (cwist_html_element_t *el, const char *id)
Set the DOM id attribute for an element.
void cwist_html_element_add_class (cwist_html_element_t *el, const char *class_name)
Append a CSS class token to an element.
void cwist_html_element_set_text (cwist_html_element_t *el, const char *text)
Replace the element's inner text payload.
void cwist_html_element_add_child (cwist_html_element_t *el, cwist_html_element_t *child)
Append a child node to an element's ordered children list.
cwist_sstring * cwist_html_render (cwist_html_element_t *el)
Render an HTML tree to a freshly allocated string buffer.
Detailed Description
Minimal HTML tree construction and rendering helpers.
Definition in file builder.c.
Function Documentation
cwist_html_element_add_attr()
void cwist_html_element_add_attr (cwist_html_element_t * el, const char * key, const char * value)
Insert or replace an HTML attribute on an element.
Parameters
el Element to update.
key Attribute name, for example "class".
value Attribute value stored as a cJSON string node.
Definition at line 61 of file builder.c.
Referenced by cwist_html_element_add_class(), and cwist_html_element_set_id().
cwist_html_element_add_child()
void cwist_html_element_add_child (cwist_html_element_t * el, cwist_html_element_t * child)
Append a child node to an element's ordered children list.
Parameters
el Parent element that will own the child.
child Child node to append.
Definition at line 122 of file builder.c.
cwist_html_element_add_class()
void cwist_html_element_add_class (cwist_html_element_t * el, const char * class_name)
Append a CSS class token to an element.
Parameters
el Element to update.
class_name Class token to append or initialise.
Definition at line 85 of file builder.c.
References cwist_html_element_add_attr(), and cwist_sstring_create().
cwist_html_element_create()
cwist_html_element_t * cwist_html_element_create (const char * tag)
Allocate a new HTML element node for the supplied tag name.
Parameters
tag Tag name to copy into the node, such as "div" or "span".
Returns
Newly allocated element, or NULL when allocation fails.
Definition at line 19 of file builder.c.
References cwist_sstring_create().
cwist_html_element_destroy()
void cwist_html_element_destroy (cwist_html_element_t * el)
Recursively destroy an element and every descendant it owns.
Parameters
el Element tree root to release. NULL is ignored.
Definition at line 37 of file builder.c.
References cwist_html_element_destroy().
Referenced by cwist_html_element_destroy().
cwist_html_element_set_id()
void cwist_html_element_set_id (cwist_html_element_t * el, const char * id)
Set the DOM id attribute for an element.
Parameters
el Element to update.
id Identifier value to assign.
Definition at line 76 of file builder.c.
References cwist_html_element_add_attr().
cwist_html_element_set_text()
void cwist_html_element_set_text (cwist_html_element_t * el, const char * text)
Replace the element's inner text payload.
Parameters
el Element to update.
text Plain-text payload to store.
Definition at line 107 of file builder.c.
References cwist_sstring_create().
cwist_html_render()
cwist_sstring * cwist_html_render (cwist_html_element_t * el)
Render an HTML tree to a freshly allocated string buffer.
Parameters
el Root element to serialise.
Returns
Rendered HTML buffer, or NULL when the root is invalid.
Definition at line 179 of file builder.c.
References cwist_sstring_create().